// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/achievements': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/achievements/index.get').default>>>>
    }
    '/api/auth/invitations/accept': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/invitations/accept.post').default>>>>
    }
    '/api/auth/invitations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/invitations/index.get').default>>>>
    }
    '/api/auth/onboarding/complete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/onboarding/complete.post').default>>>>
    }
    '/api/auth/onboarding': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/onboarding/index.get').default>>>>
    }
    '/api/auth/otp/request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/otp/request.post').default>>>>
    }
    '/api/auth/otp/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/otp/verify.post').default>>>>
    }
    '/api/auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/session.delete').default>>>>
    }
    '/api/companies/slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/companies/slug.get').default>>>>
    }
    '/api/dashboard/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/summary.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/invitations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invitations/[id].delete').default>>>>
    }
    '/api/invitations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invitations/index.get').default>>>>
    }
    '/api/leaderboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leaderboard.get').default>>>>
    }
    '/api/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me.get').default>>>>
    }
    '/api/members/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].patch').default>>>>
    }
    '/api/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.get').default>>>>
    }
    '/api/members/invite': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/invite.post').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/rewards': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rewards/index.get').default>>>>
    }
    '/api/tasks/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id].patch').default>>>>
    }
    '/api/tasks/:id/attachments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/attachments.post').default>>>>
    }
    '/api/tasks/:id/comments': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/comments.post').default>>>>
    }
    '/api/tasks/:id/progress': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/progress.patch').default>>>>
    }
    '/api/tasks/:id/transition': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[id]/transition.post').default>>>>
    }
    '/api/tasks/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/dashboard.get').default>>>>
    }
    '/api/tasks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/index.post').default>>>>
    }
    '/api/teams/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id].patch').default>>>>
    }
    '/api/teams/:id/members': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/members.post').default>>>>
    }
    '/api/teams/:id/members/:userId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/members/[userId].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/[id]/members/[userId].patch').default>>>>
    }
    '/api/teams': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}