// Generated by auto imports
export {}
declare global {
  const useRuntimeConfig: (event?: import('h3').H3Event) => import('nuxt/schema').RuntimeConfig
  const useAppConfig: () => import('nuxt/schema').AppConfig
  const defineAppConfig: <C extends import('nuxt/schema').AppConfigInput>(config: C) => C
  const createError: typeof import('h3')['createError']
  const setResponseStatus: typeof import('h3')['setResponseStatus']
  const ACTIVE_TASK_STATUSES: typeof import('../../shared/utils/task').ACTIVE_TASK_STATUSES
  const CLOSED_TASK_STATUSES: typeof import('../../shared/utils/task').CLOSED_TASK_STATUSES
  const OPEN_TASK_STATUSES: typeof import('../../shared/utils/task').OPEN_TASK_STATUSES
  const PERMISSIONS: typeof import('../../shared/utils/permissions').PERMISSIONS
  const PRIORITY_WEIGHT: typeof import('../../shared/utils/task').PRIORITY_WEIGHT
  const REVIEW_DECISIONS: typeof import('../../shared/utils/task').REVIEW_DECISIONS
  const ROLES: typeof import('../../shared/utils/permissions').ROLES
  const ROLE_RANK: typeof import('../../shared/utils/permissions').ROLE_RANK
  const TASK_ACTIONS: typeof import('../../shared/utils/task').TASK_ACTIONS
  const TASK_PRIORITIES: typeof import('../../shared/utils/task').TASK_PRIORITIES
  const TASK_STATUSES: typeof import('../../shared/utils/task').TASK_STATUSES
  const TASK_TRANSITIONS: typeof import('../../shared/utils/task').TASK_TRANSITIONS
  const availableActions: typeof import('../../shared/utils/task').availableActions
  const calendarLocale: typeof import('../../shared/utils/format').calendarLocale
  const can: typeof import('../../shared/utils/permissions').can
  const canEditTeam: typeof import('../../shared/utils/member-scope').canEditTeam
  const canLeadRole: typeof import('../../shared/utils/member-scope').canLeadRole
  const canTransition: typeof import('../../shared/utils/task').canTransition
  const checkTransition: typeof import('../../shared/utils/task').checkTransition
  const completionRate: typeof import('../../shared/utils/task').completionRate
  const computeLevelProgress: typeof import('../../shared/utils/xp').computeLevelProgress
  const daysUntilDue: typeof import('../../shared/utils/task').daysUntilDue
  const defaultMinXp: typeof import('../../shared/utils/xp').defaultMinXp
  const findTransition: typeof import('../../shared/utils/task').findTransition
  const formatCompactNumber: typeof import('../../shared/utils/format').formatCompactNumber
  const formatDate: typeof import('../../shared/utils/format').formatDate
  const formatNumber: typeof import('../../shared/utils/format').formatNumber
  const formatPercent: typeof import('../../shared/utils/format').formatPercent
  const formatPhone: typeof import('../../shared/utils/format').formatPhone
  const formatRelativeDate: typeof import('../../shared/utils/format').formatRelativeDate
  const isDueToday: typeof import('../../shared/utils/task').isDueToday
  const isOverdue: typeof import('../../shared/utils/task').isOverdue
  const isRole: typeof import('../../shared/utils/permissions').isRole
  const isTaskAction: typeof import('../../shared/utils/task').isTaskAction
  const isTaskStatus: typeof import('../../shared/utils/task').isTaskStatus
  const maxAssignableRole: typeof import('../../shared/utils/member-scope').maxAssignableRole
  const memberPermissions: typeof import('../../shared/utils/member-scope').memberPermissions
  const nextStatus: typeof import('../../shared/utils/task').nextStatus
  const normalizeIranianPhone: typeof import('../../shared/utils/format').normalizeIranianPhone
  const numberLocale: typeof import('../../shared/utils/format').numberLocale
  const resolveLevel: typeof import('../../shared/utils/xp').resolveLevel
  const roleAtLeast: typeof import('../../shared/utils/permissions').roleAtLeast
  const roleAtMost: typeof import('../../shared/utils/member-scope').roleAtMost
  const slugify: typeof import('../../shared/utils/format').slugify
  const streakProgressPercent: typeof import('../../shared/utils/xp').streakProgressPercent
  const visibleMemberScope: typeof import('../../shared/utils/member-scope').visibleMemberScope
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ScopeSubject, MemberTarget, MemberPermissions } from '../../shared/utils/member-scope'
  import('../../shared/utils/member-scope')
  // @ts-ignore
  export type { Role, Permission } from '../../shared/utils/permissions'
  import('../../shared/utils/permissions')
  // @ts-ignore
  export type { TaskStatus, TaskPriority, ReviewDecision, TaskAction, TaskActorKind, TaskTransition, TaskActorContext, TransitionCheck } from '../../shared/utils/task'
  import('../../shared/utils/task')
  // @ts-ignore
  export type { LevelBoundary, LevelProgress } from '../../shared/utils/xp'
  import('../../shared/utils/xp')
  // @ts-ignore
  export type { ApiErrorBody, AuthContext, Paginated, MeResponse, CompanySummary, UserSummary, RequestOtpResponse, VerifyOtpResponse, OnboardingContext, CompleteOnboardingResponse, SlugAvailabilityResponse, InvitationStatus, TeamRole, UserStatus, MemberSummary, MemberListResponse, MemberDetail, MemberDetailResponse, InvitationSummary, InvitationListResponse, InvitationDetail, PendingInvitationResponse, TeamSummary, TeamDetail, TeamDetailResponse, AcceptInvitationResponse, TaskPerson, TaskComment, TaskAttachment, TaskReviewEntry, TaskEventEntry, TaskListResponse, TaskDetailResponse, TaskMutationResponse, TeamCompletionRow, TaskDashboardResponse } from '../../shared/types/api'
  import('../../shared/types/api')
}